
import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import fs from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.resolve(__dirname, '../.env') });

const supabase = createClient(process.env.VITE_SUPABASE_URL, process.env.VITE_SUPABASE_ANON_KEY);

async function generateSQL() {
    console.log("Identifying duplicates for SQL generation...");

    const { data: allocations, error } = await supabase
        .from('trial_allocations')
        .select(`
            allocation_id,
            workflow_id,
            created_at,
            player_workflow (
                workflow_id,
                email,
                phone,
                registration_id
            )
        `);

    if (error) { console.error(error); return; }

    const phoneMap = new Map();
    allocations.forEach(r => {
        const wf = r.player_workflow;
        if (!wf) return;
        const phone = wf.phone ? String(wf.phone).replace(/[^0-9]/g, '').slice(-10) : 'NO_PHONE';
        if (phone !== 'NO_PHONE') {
            if (!phoneMap.has(phone)) phoneMap.set(phone, []);
            phoneMap.get(phone).push(r);
        }
    });

    let allocIds = [];
    let wfIds = [];
    let regIds = [];

    for (const [phone, records] of phoneMap) {
        if (records.length > 1) {
            // Sort: Keep Oldest
            records.sort((a, b) => new Date(a.created_at) - new Date(b.created_at));
            const removers = records.slice(1);

            removers.forEach(dub => {
                allocIds.push(dub.allocation_id);
                wfIds.push(dub.workflow_id);
                if (dub.player_workflow?.registration_id) {
                    regIds.push(dub.player_workflow.registration_id);
                }
            });
        }
    }

    if (allocIds.length === 0) {
        console.log("No duplicates found to clean.");
        return;
    }

    console.log(`Found ${allocIds.length} duplicates.`);

    // Generate SQL
    const formatList = (list) => list.map(id => `'${id}'`).join(',\n    ');

    const sql = `
-- Cleanup Duplicates SQL
-- Generated by Antigravity
-- Total Duplicates Found: ${allocIds.length}

BEGIN;

-- 1. Delete Allocations
DELETE FROM trial_allocations 
WHERE allocation_id IN (
    ${formatList(allocIds)}
);

-- 2. Delete Workflows
DELETE FROM player_workflow 
WHERE workflow_id IN (
    ${formatList(wfIds)}
);


COMMIT;
    `;

    fs.writeFileSync('cleanup_duplicates.sql', sql);
    console.log("SQL file generated: cleanup_duplicates.sql");
}

generateSQL();
